### ISSUE TITLE
Ambiguity involving level-order traversal

### ISSUE THREAD

**Issue by khuldraeseth** [kevincal1226/281-Tree-Deduction#1]
A level-order traversal and a pre- or postorder traversal do not together provide enough information to reconstruct a unique tree. The site sometimes gives problems that don't have a single solution:
```
Preorder Traversal:   56, 31, 35, 61, 39, 19, 33, 46
Levelorder Traversal: 56, 31, 19, 35, 61, 33, 46, 39
```
39 here could fall either before or after its parent 61 in an inorder traversal.

**Comment by kevincal1226** [comment]
Resolved. Made it so If the first randomly-chosen traversal is Levelorder, the second traversal must be Levelorder. Similarly, if the first traversal is Pre/Post order, the second traversal must be Inorder. Someone in the 281 Discord said you can reconstruct a BTree from Level + any of the other 3 so I guess that's what I get for just believing what someone said.

**Comment by khuldraeseth** [comment]
Control flow can now be simplified to how it was before. Level-order traversal is in the same category as pre- and postorder traversal and must be paired with inorder, so there's only one choice of traversal to show the user.

**Comment by kevincal1226** [comment]
> Control flow can now be simplified to how it was before. Level-order traversal is in the same category as pre- and postorder traversal and must be paired with inorder, so there's only one choice of traversal to show the user.

Resolved. I also realized this right as you commented.
